### ISSUE TITLE
ERROR: No matching distribution found for pyarrow==1.24.2

### ISSUE THREAD

**Issue by luk-brue** [MGPoirot/web2mp3#1]
When trying to install your package, I ran into this issue:
During `pip install -r requirements.txt`, I get this error.

```
ERROR: Could not find a version that satisfies the requirement pyarrow==1.24.2 (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.15.1, 0.16.0, 0.17.0, 0.17.1, 1.0.0, 1.0.1, 2.0.0, 3.0.0, 4.0.0, 4.0.1, 5.0.0, 6.0.0, 6.0.1, 7.0.0, 8.0.0, 9.0.0, 10.0.0, 10.0.1, 11.0.0, 12.0.0, 12.0.1)
ERROR: No matching distribution found for pyarrow==1.24.2
```
As far as I can see, [there is no version 1.24.2 of pyarrow](https://pypi.org/project/pyarrow/#history)

Installing it manually with `pip install pyarrow` might work, but I ran into the next error, which may or may not be related so I can not say for sure.

**Comment by MGPoirot** [comment]
Pyarrow is a package required to store serialized data as `parquet`, which is faster and storage efficient than fornexample Pickle.

However, I've noticed aswell that the installation of pyarrow can be finicky, depening on your environment.

I'll check if there is a solution to the pyarrow install or see if we need to switch data format tomorrow.

**Comment by luk-brue** [comment]
Thanks for your reply. My point is that there probably is a typo in `requirements.txt`, where you specified `pyarrow==1.24.2`. On their webpage, there is no such version. Current version is 12.0.1 or something like that.
Hope this helps.

**Comment by luk-brue** [comment]
Pyarrow itself works fine and the installation (manual, not via requirements.txt) went smoothly for me on Linux Mint 21. So you don't have to bother changing your data structure, I think.

**Comment by MGPoirot** [comment]
Indeed, the appropriate version was 12.0.0
A typo must have slipped in. Thanks checking!
