### ISSUE TITLE
Copy-Pasteable Installation Commands with Explanation

### ISSUE THREAD

**Issue by luk-brue** [MGPoirot/web2mp3#2]
I tried to follow along the Quickstart Video, which made me install miniconda. Python already existed on my PC. 
Miniconda installed an additional version of python to a different location on my computer. Now some packages need to be installed in both python locations, depending on stuff I do not understand, to make everything work. I ended up installing all requirements manually with `pip install …`, because I got errors (like below) even though I ran `pip install -r requirements.txt` before. 

Example error:

```
python ~/apps/web2mp3/src/main.py


Traceback (most recent call last):
  File "/home/elbe/apps/web2mp3/src/main.py", line 3, in <module>
    from initialize import log_dir
  File "/home/elbe/apps/web2mp3/src/initialize.py", line 1, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'
```

**Comment by MGPoirot** [comment]
Hi! Thanks for the report. 
What is your OS? 
Did you install the requirements with pip or conda? 

I checked, and `python-dotenv==1.0.0` is correctly in yhe requirements file, so it might be that the installation of the requirements on your machine failed for some reason.


I will attempt a clean install tomorrow, to check if everything is OK on this side. I'll also update the README, since thats been long due after recent updates.

**Comment by luk-brue** [comment]
Yes, this issue is related to me only I think, because I am clueless in how to handle python and conda... 
My OS is Linux Mint 21.
I installed via `pip` while being in a conda environment. Then later I installed again while not being in that environment. Because it did not work earlier.

Having multiple paths for packages and versions of python (the one thats shipped with Linux + the one that comes with conda) was a little overwhelming.

The core point for opening an issue here was not a specific package missing, but rather the whole thing that all the packages I installed with pip were not found in conda. Probably this is a user  error and no bug. I suspect this happened because packages were installed to a location which was not on my PATH variable.

This might be just specific to me, but what you could do to enhance usability is to put some commented installation walkthrough with some explanations into the readme. The video is nice, but I can not copy paste from it.

Best wishes! 
P.S. Due to not wanting to get much more involved with PATH variables and such things, I decided to use [spotify-downloader](https://github.com/spotDL/spotify-downloader)
 Do you know this project?

**Comment by luk-brue** [comment]
That being said, I really appreciate your efforts because web2mp3 goes some steps further than spotdl:

- has support for saving in directory structure
- can download from YouTube URL directly, useful for cases where song is not on spotify, spotdl can not do that. Because maybe I do not want to use yt-dlp manually for this case, but rather have that use case integrated in the same app
- and for sure there is more to be said.

**Comment by MGPoirot** [comment]
Hey there,
Thanks for your suggestion, I have added the installation commands to the README. I've checked them and they are functional on Win10 and RedHat:
```
git clone https://github.com/MGPoirot/web2mp3.git
cd web2mp3
conda create -n demo_env
conda activate demo_env
pip install -r requirements.txt
python src/main.py
[enter Spotify Client ID and Secret]
https://www.youtube.com/watch?v=N4bFqW_eu2I
``` 
Thanks for the appreciation, there really are some cool functionalities; I'm working on improving the documentation and providing a better demo of all functionalities soon.
Let me know if it works for you!
